In [15]:
import tensorflow as tf

In [16]:
A = tf.constant([[1,2,3],[4,5,6]])
B = tf.constant([[0,0],[1,0],[0,1]])

In [17]:
resultado = tf.matmul(A,B)

In [18]:
print(tf.Session().run(resultado))

[[2 3]
 [5 6]]


In [19]:
x = tf.constant([0,1,0])
#adiciona uma dimensão para possibilitar a multiplicação em vez de 0 colunas aparece 1 coluna.
x = tf.expand_dims(x,1)


In [20]:
resultado2 = tf.matmul(A,x)

In [21]:
print(tf.Session().run(resultado2))

[[2]
 [5]]


In [24]:
print(tf.Session().run(A))
transposta = tf.transpose(A)
print(tf.Session().run(transposta))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
